export function localImages() {
  return {
    intro1: require("./images/intro1.png"),
    intro2: require("./images/intro2.png"),
    intro3: require("./images/intro3.png"),
    githubIcon: require("./images/githubIcon.png"),
    googleIcon: require("./images/googleIcon.png"),
    btnBack: require("./images/btnBack.png"),
    bg: require("./images/bg.png"),
    arrBackIcon: require("./images/arrBackIcon.png"),

    // ============= icon bottom tab
    micIcon: require("./bottomTabIcon/micIcon.png"),
    micActiveIcon: require("./bottomTabIcon/micActiveIcon.png"),
    homeIcon: require("./bottomTabIcon/homeIcon.png"),
    homeActiveIcon: require("./bottomTabIcon/homeActiveIcon.png"),
    scheduleActiveIcon: require("./bottomTabIcon/scheduleActiveIcon.png"),
    scheduleIcon: require("./bottomTabIcon/scheduleIcon.png"),
    userIcon: require("./bottomTabIcon/userIcon.png"),
    userActiveIcon: require("./bottomTabIcon/userActiveIcon.png"),
    searchIconActive: require("./bottomTabIcon/searchIconActive.png"),

    //
    filterIcon: require("./images/filterIcon.png"),
    searchIcon: require("./images/searchIcon.png"),
    locationItemIcon: require("./images/locationItemIcon.png"),
    arrowNextIcon: require("./images/arrowNextIcon.png"),
    exitIcon: require("./images/exitIcon.png"),
    destinationIcon: require("./images/destinationIcon.png"),
    originIcon: require("./images/originIcon.png"),
    pointIcon: require("./images/pointIcon.png"),
    transactionIcon: require("./images/transactionIcon.png"),
    stepIcon: require("./images/stepIcon.png"),
    footIcon: require("./images/footIcon.png"),
    carIcon: require("./images/carIcon.png"),
    motorbikeIcon: require("./images/motorbikeIcon.png"),
    bycicleIcon: require("./images/bycicleIcon.png"),
    googleMapIcon: require("./images/googleMapIcon.png"),
    saveLocationIcon: require("./images/saveLocationIcon.png"),
    addIcon: require("./images/addIcon.png"),
    trashIcon: require("./images/trashIcon.png"),
    foodIcon: require("./images/foodIcon.png"),
    locationIcon: require("./images/locationIcon.png"),
    suggestIcon: require("./images/suggest.png"),
    voiceIcon: require("./images/voice.png"),
  };
}
